#!/usr/bin/env bash
set -euo pipefail

# setup_nginx_certbot_bakamousa.sh
# Run this on the Lightsail instance (Ubuntu/Debian). It will:
#  - install nginx, certbot
#  - add an nginx site for bakamousa.com (proxy to 127.0.0.1:3000)
#  - add a redirect from bakamousa.bakamosocial.com -> bakamousa.com
#  - request certificates for bakamousa.com + bakamousa.bakamosocial.com
#  - reload nginx

# USAGE:
#  sudo bash setup_nginx_certbot_bakamousa.sh bakamousa.com bakamousa.bakamosocial.com
# Note: ensure the domains point to this server's IP before running certbot.

if [ "$EUID" -ne 0 ]; then
  echo "This script must be run as root (use sudo)"
  exit 1
fi

if [ $# -lt 2 ]; then
  echo "Usage: $0 <PRIMARY_DOMAIN> <SUBDOMAIN_TO_REDIRECT>"
  echo "Example: $0 bakamousa.com bakamousa.bakamosocial.com"
  exit 1
fi

PRIMARY_DOMAIN="$1"
SUBDOMAIN="$2"
WWW_DOMAIN="www.$PRIMARY_DOMAIN"
NGINX_SITE="/etc/nginx/sites-available/$PRIMARY_DOMAIN"
NGINX_ENABLED="/etc/nginx/sites-enabled/$PRIMARY_DOMAIN"

echo "Installing packages (nginx, certbot)..."
apt update
apt install -y nginx certbot python3-certbot-nginx

echo "Creating nginx site config: $NGINX_SITE"
cat > "$NGINX_SITE" <<EOF
# Generated by setup_nginx_certbot_bakamousa.sh
# Basic HTTP site that proxies the primary domain to the local Next.js server
server {
  listen 80;
  server_name $PRIMARY_DOMAIN $WWW_DOMAIN;

  # Proxy all requests to Next.js running on 127.0.0.1:3000
  location / {
    proxy_pass http://127.0.0.1:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_cache_bypass $http_upgrade;
  }
}

# Redirect old subdomain to the primary domain over HTTPS (will be converted by certbot)
server {
  listen 80;
  server_name $SUBDOMAIN;
  return 301 https://$PRIMARY_DOMAIN$request_uri;
}
EOF

# Enable site
ln -sf "$NGINX_SITE" "$NGINX_ENABLED"

# Test nginx config and reload
nginx -t && systemctl reload nginx

# Allow firewall for nginx (if ufw present)
if command -v ufw >/dev/null 2>&1; then
  echo "Configuring UFW to allow 'Nginx Full' (ports 80/443)"
  ufw allow 'Nginx Full' || true
fi

# Run certbot to obtain certs and update nginx config
echo "Running certbot for: $PRIMARY_DOMAIN, $WWW_DOMAIN, $SUBDOMAIN"
certbot --nginx -d "$PRIMARY_DOMAIN" -d "$WWW_DOMAIN" -d "$SUBDOMAIN" --non-interactive --agree-tos --email "admin@$PRIMARY_DOMAIN"

# Ensure nginx reload
systemctl reload nginx

cat <<MSG
Done.
- Nginx site created at $NGINX_SITE
- Certificates requested and auto-configured by Certbot

Next steps:
- Start your Next.js app (example using pm2):
    npm install --production
    npm run build
    npm i -g pm2
    pm2 start npm --name bakamousa -- start
    pm2 save
    pm2 startup

- Verify HTTPS: https://$PRIMARY_DOMAIN
- Test preview endpoint: https://$PRIMARY_DOMAIN/api/preview?secret=<WP_PREVIEW_SECRET>&slug=<slug>

If certbot fails to issue a certificate, ensure DNS records for all domains resolve to this server and try again.
MSG
